services:
  - type: web
    name: coffee-shop-backend
    env: docker
    plan: free
    branch: main
    dockerfilePath: backend/Dockerfile
    buildFilter:
      paths:
        - backend/**
    autoDeploy: true
